### ISSUE TITLE
Distribute LICENSE file on PyPI

### ISSUE THREAD

**Issue by ignatenkobrain** [ns1/ns1-python#31]
Hello,

https://files.pythonhosted.org/packages/source/n/ns1-python/ns1-python-0.9.19.tar.gz is missing license file. I'm working on packaging ns1-python for Fedora/EPEL where we require shipping license file. Would appreciate if you could release new version with LICENSE file included.

Thanks in advance!

**Comment by mburtless** [comment]
`v0.10.0` has been released, which includes a LICENSE file.

**Comment by ignatenkobrain** [comment]
Thanks! I've submitted updates to Fedora/EPEL:

* https://bodhi.fedoraproject.org/updates/FEDORA-2019-a6810388bb
* https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-cf050b260e
