### ISSUE TITLE
zones.list does not support getting more than 2500 zones. 

### ISSUE THREAD

**Issue by shalomcarmel** [ns1/ns1-python#43]
The API documentation specifies to use the Link response header in order to page through more than 2500 results. 
Atm, it seems that this sdk will always fetch only the first 2500 zones in an account, ignoring the rest.

**Comment by rupa** [comment]
Yep, apologies. this is a known issue - we need to add pagination support in the py-SDK. It's in the backlog. If you need it ASAP I'd encourage you to contact support, so they can work with you on prioritizing this and working things out so everyone is happy, and/or we'd be happy to take a look at a PR if you are so inclined.

Note: we also paginate (just) the records in zone responses - just a heads up in case it's relevant to you.

**Comment by rupa** [comment]
pagination support has just been merged, PyPI release will be coming soon. It's off by default, to keep from being a breaking change, so needs to be enabled in config, e.g. `config["follow_pagination"] = True`

apologies for the wait. I'm going to close this ticket, but feel free to file a new issue or reopen this one if you run across any problems.
