### ISSUE TITLE
bump tag

### ISSUE THREAD

**Issue by dch** [ns1/ns1-python#53]
hey folks, I maintain the [FreeBSD port](https://www.freshports.org/dns/py-ns1-python) and it looks like you've got a few changes since the last tagged release. If you tag it I will update the port again!

**Comment by rupa** [comment]
Hi, yep, this is my fault - I was planning to merge a few more things before doing a release, to keep change noise down, but things took longer than anticipated and it's not worth waiting. We'll get latest changes tagged up ASAP. thanks for the nudge
