### ISSUE TITLE
Unable to pull records for zones in `co.uk`

### ISSUE THREAD

**Issue by alwaysjolley** [ns1/ns1-python#57]
receiving a `record not found` when trying to pull records for zones in the `co.uk` TLD.

This works fine for all other zones
```
nsone = ns1.NS1(apiKey="redacted")
records = nsone.loadRecord('example.co.uk', 'NS')
print (records)
```

**Comment by alwaysjolley** [comment]
user zone, third param, to force the zone and not try to extract the zone from the node

**Comment by rupa** [comment]
Glad you got it sorted out. Thanks for bringing this up though - the documentation is not quite accurate for that function, which doesn't help, so I'm going to try and get that improved a bit
