### ISSUE TITLE
Secondary Zone

### ISSUE THREAD

**Issue by ckajrolkar** [ns1/ns1-python#61]
How we can create Secondary Zone with primary, secondary ip
wit TSIG key

**Comment by mburtless** [comment]
Hi @ckajrolkar - I'm not totally sure I understand the use case.  If you're creating a Secondary zone, that would typically only require a primary IP (and, optionally, additional primary IPs).  Secondary IPs are typically used by Primary zones.

Here's a simple example of creating a secondary zone with a primary IP and a TSIG key:
```
from ns1 import NS1, Config

config = Config()
config.createFromAPIKey("qACMD09OJXBxT7XOuRs8")
api = NS1(config=config)
zone = api.createZone(
    "examplesecondary.test",
    secondary={
        "enabled": True,
        "primary_ip": "1.2.3.4",
        "tsig": {
            "enabled": True,
            "hash": "hmac-md5",
            "name": "example-key",
            "key": "mwmF7XOq/cB0TSF6kJX+sNW2jkZU/s0V/KPfXtOa6tTk3wU3RuZBFjM10 H0ATD+qbCdC7n64L9QqkAvk3sh89xw==",
        },
    },
)
print(zone)
```

I'm going to close this issue out, but feel free to reopen this issue or open a new issue if you have further questions here.

**Comment by ckajrolkar** [comment]
Great..thank you
