### ISSUE TITLE
How to create CNAME record for the naked zone?

### ISSUE THREAD

**Issue by al-jeyapal** [ns1/ns1-python#9]
We can create a CNAME record for the domain using the web interface but not the Python API.
Is it possible to place a CNAME record at the apex?

E.g. For a zone: example.com:

```
# point example.com at real.com
zone.add_CNAME("", "real.com")
```

The above fails:

> ns1.rest.errors.ResourceException: server error: ".example.com" not a valid domain in example.com

**Comment by stuffcarlcodes** [comment]
Using a CNAME record at the apex breaks RFC, but we do have an ALIAS record which behaves like a CNAME and does some pre-fetching to return an IP as expected instead. This will work well for you.

**Comment by al-jeyapal** [comment]
Okay great. It is possible to create the ALIAS record using this Python API?

I can't seem to create a A record or the ALIAS record in the zone for the apex:
```
zone.add_ALIAS('', 'real.com')
-> ns1.rest.errors.ResourceException: server error: ".example.com" not a valid domain in example.com

zone.add_A('', ['1.2.3.4'])
-> ns1.rest.errors.ResourceException: server error: ".example.com" not a valid domain in example.com
```

Is it possible to add apex records using the Python API?

**Comment by fcelda** [comment]
@al-jeyapal The library complains about the record name. The logic is a bit twisted - if the provided record name doesn't end with zone name, the zone name is always appended to the record name: https://github.com/ns1/ns1-python/blob/f00038c1b9472b7af344279047a3bf03bfe1ce71/ns1/records.py#L32-L33

Something like this should work:

```py
zone.add_ALIAS('example.com', 'real.com')
```

**Comment by al-jeyapal** [comment]
Thanks @fcelda, that works perfectly.
